# Generated by Django 3.1.6 on 2021-02-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.IntegerField(choices=[(0, 'Drafts'), (1, 'publish')], default=0),
        ),
    ]
