# Generated by Django 3.1.6 on 2021-02-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210203_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='body',
        ),
    ]
