# Generated by Django 3.1.6 on 2021-02-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
