# Generated by Django 3.1.6 on 2021-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210203_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='images',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
