# Generated by Django 3.1.6 on 2021-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articles_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
