# Generated by Django 3.1.6 on 2021-02-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210203_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='images',
        ),
    ]
